---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: data
  label: Data
  create: all
  match: "**/*"
  new_doc_ext: yml
  templates:
  - meta
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/products
  label: Products
  create: all
  match: "**/*"
  templates:
  - product
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
  templates:
  - basic_page
  - team
- type: directory
  path: content/gallery
  label: Gallery
  create: all
  match: "**/*"
  templates:
  - album
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.48'
