---
label: product
hide_body: false
is_partial: false
fields:
- type: blocks
  name: seo
  label: SEO
  config:
    min: '1'
    max: '1'
  template_types:
  - seo
- type: textarea
  label: Short Description
  name: short_description
