---
label: product
hide_body: false
is_partial: false
fields:
- type: blocks
  name: seo
  label: SEO
  config:
    min: '1'
    max: '1'
  template_types:
  - seo
- type: textarea
  label: Short Description
  name: short_description
- type: file
  name: main_picture
  label: Main Picture
- type: image_gallery
  name: other_pictures
  label: Other Pictures
- type: image_gallery
  name: product_files
  label: Product Files
- type: text
  name: feature_title
  label: Feature Title
- type: list
  name: features
  label: Features
  config:
    use_select: false
    source:
      type: pages
  hidden: false
- type: blocks
  name: highlights
  label: Highlights
  template_types:
  - highlight
