---
label: product
hide_body: false
is_partial: false
fields:
- type: blocks
  name: seo
  label: SEO
  config:
    min: '1'
    max: '1'
  template_types:
  - seo
- type: textarea
  label: Short Description
  name: short_description
- type: file
  name: main_picture
  label: Main Picture
- type: image_gallery
  name: other_pictures
  label: other_pictures
- type: image_gallery
  name: product_files
  label: product_files
